# Generated by Django 3.2.3 on 2021-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='example_name_here', max_length=30),
            preserve_default=False,
        ),
    ]
