# Generated by Django 3.2.4 on 2021-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210620_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='photosubmission',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='pic'),
        ),
    ]
